import { initializeApp, cert, getApps } from "firebase-admin/app";
import { getFirestore, FieldValue } from "firebase-admin/firestore";

export const dynamic = "force-dynamic";
export const maxDuration = 60;

function getDb() {
  if (!getApps().length) {
    const cred = process.env.FIREBASE_SERVICE_ACCOUNT_KEY;
    if (cred) {
      try {
        initializeApp({ credential: cert(JSON.parse(cred)) });
      } catch (e) {
        console.error("[PUBLISH] Invalid FIREBASE_SERVICE_ACCOUNT_KEY JSON:", e.message);
        initializeApp({ projectId: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID });
      }
    } else {
      initializeApp({ projectId: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID });
    }
  }
  return getFirestore();
}

/**
 * POST /api/factory/publish
 *
 * Publishes a completed video to YouTube via the Data API.
 * Handles: upload, metadata (title, desc, tags, category),
 * thumbnail upload, playlist assignment, and scheduling.
 *
 * Actions: publish, schedule, update-metadata
 */
export async function POST(req) {
  try {
    const body = await req.json();
    const { action, userId } = body;

    if (!userId) return Response.json({ error: "userId required" }, { status: 400 });

    const db = getDb();
    const pipesRef = db.collection("users").doc(userId).collection("factory_pipelines");

    // Get user's Google access token from Firestore
    async function getGoogleToken() {
      const tokenDoc = await db.collection("users").doc(userId).collection("tokens").doc("google").get();
      if (!tokenDoc.exists) return null;
      const data = tokenDoc.data();

      // Check if token is expired
      if (data.expiresAt && new Date(data.expiresAt) < new Date()) {
        // Refresh the token
        if (data.refreshToken) {
          try {
            const refreshRes = await fetch("https://oauth2.googleapis.com/token", {
              method: "POST",
              headers: { "Content-Type": "application/x-www-form-urlencoded" },
              body: new URLSearchParams({
                client_id: process.env.GOOGLE_CLIENT_ID,
                client_secret: process.env.GOOGLE_CLIENT_SECRET,
                refresh_token: data.refreshToken,
                grant_type: "refresh_token",
              }),
            });
            const refreshData = await refreshRes.json();
            if (refreshData.access_token) {
              await db.collection("users").doc(userId).collection("tokens").doc("google").update({
                accessToken: refreshData.access_token,
                expiresAt: new Date(Date.now() + refreshData.expires_in * 1000).toISOString(),
              });
              return refreshData.access_token;
            }
          } catch (err) {
            console.error("[TOKEN REFRESH]", err);
          }
        }
        return null;
      }

      return data.accessToken;
    }

    /* ── PUBLISH — upload video to YouTube ── */
    if (action === "publish") {
      const { pipelineId, channelId, privacy, scheduledPublishAt } = body;
      if (!pipelineId) return Response.json({ error: "pipelineId required" }, { status: 400 });

      const pipeDoc = await pipesRef.doc(pipelineId).get();
      if (!pipeDoc.exists) return Response.json({ error: "Pipeline not found" }, { status: 404 });
      const pipe = pipeDoc.data();

      const script = pipe.assets?.script;
      if (!script) return Response.json({ error: "No script in pipeline — generate one first" }, { status: 400 });

      const accessToken = await getGoogleToken();
      if (!accessToken) {
        return Response.json({
          error: "No valid Google access token. Re-authenticate via YouTube module.",
          requiresAuth: true,
        }, { status: 401 });
      }

      // Build YouTube metadata
      const metadata = {
        snippet: {
          title: script.title || pipe.topic,
          description: script.description || `${pipe.topic}\n\nGenerated by Antigravity Factory`,
          tags: script.tags || [],
          categoryId: getCategoryId(script.category || "Entertainment"),
          defaultLanguage: "en",
        },
        status: {
          privacyStatus: privacy || (scheduledPublishAt ? "private" : "public"),
          selfDeclaredMadeForKids: false,
          embeddable: true,
          publicStatsViewable: true,
        },
      };

      // If scheduled, set publish time
      if (scheduledPublishAt) {
        metadata.status.publishAt = new Date(scheduledPublishAt).toISOString();
        metadata.status.privacyStatus = "private"; // Must be private for scheduling
      }

      // If channel specified via onBehalfOfContentOwner
      const channelParam = channelId ? `&onBehalfOfContentOwnerChannel=${channelId}` : "";

      // Step 1: If we have a final video URL, download and upload
      const videoUrl = pipe.assets?.finalVideoUrl;
      if (!videoUrl) {
        // No composed video — upload as metadata-only, mark for manual upload
        const metaRes = await fetch(
          `https://www.googleapis.com/youtube/v3/videos?part=snippet,status${channelParam}`,
          {
            method: "POST",
            headers: {
              Authorization: `Bearer ${accessToken}`,
              "Content-Type": "application/json",
            },
            body: JSON.stringify(metadata),
          }
        );

        if (!metaRes.ok) {
          const errData = await metaRes.json();
          await pipesRef.doc(pipelineId).update({
            error: `YouTube API: ${errData.error?.message || metaRes.status}`,
          });
          return Response.json({ error: errData.error?.message || "Upload failed" }, { status: metaRes.status });
        }

        const videoData = await metaRes.json();

        await pipesRef.doc(pipelineId).update({
          state: "PUBLISHED",
          "assets.youtubeVideoId": videoData.id,
          "assets.youtubeUrl": `https://youtu.be/${videoData.id}`,
          updatedAt: new Date().toISOString(),
          stateHistory: FieldValue.arrayUnion({
            state: "PUBLISHED",
            at: new Date().toISOString(),
            note: "Metadata-only upload — no final video composed yet",
          }),
        });

        return Response.json({
          published: true,
          videoId: videoData.id,
          url: `https://youtu.be/${videoData.id}`,
          note: "Metadata uploaded. No video file — compose step was skipped.",
        });
      }

      // Download the video file
      let videoRes;
      try {
        videoRes = await fetch(videoUrl);
      } catch (err) {
        return Response.json({ error: `Failed to fetch video file: ${err.message}` }, { status: 500 });
      }
      if (!videoRes.ok) {
        return Response.json({ error: `Failed to download video: ${videoRes.status}` }, { status: 500 });
      }
      const videoBuffer = await videoRes.arrayBuffer();

      // Resumable upload to YouTube
      const initRes = await fetch(
        `https://www.googleapis.com/upload/youtube/v3/videos?uploadType=resumable&part=snippet,status${channelParam}`,
        {
          method: "POST",
          headers: {
            Authorization: `Bearer ${accessToken}`,
            "Content-Type": "application/json; charset=UTF-8",
            "X-Upload-Content-Length": videoBuffer.byteLength,
            "X-Upload-Content-Type": "video/mp4",
          },
          body: JSON.stringify(metadata),
        }
      );

      if (!initRes.ok) {
        const errData = await initRes.json();
        return Response.json({ error: errData.error?.message || "Upload init failed" }, { status: initRes.status });
      }

      const uploadUrl = initRes.headers.get("location");

      // Upload the actual video
      const uploadRes = await fetch(uploadUrl, {
        method: "PUT",
        headers: {
          "Content-Type": "video/mp4",
          "Content-Length": videoBuffer.byteLength,
        },
        body: videoBuffer,
      });

      if (!uploadRes.ok) {
        return Response.json({ error: `Video upload failed: ${uploadRes.status}` }, { status: uploadRes.status });
      }

      const videoData = await uploadRes.json();

      // Upload thumbnail if we have one
      if (pipe.assets?.thumbnailUrl) {
        try {
          const thumbRes = await fetch(pipe.assets.thumbnailUrl);
          const thumbBuffer = await thumbRes.arrayBuffer();

          await fetch(
            `https://www.googleapis.com/upload/youtube/v3/thumbnails/set?videoId=${videoData.id}`,
            {
              method: "POST",
              headers: {
                Authorization: `Bearer ${accessToken}`,
                "Content-Type": "image/png",
              },
              body: thumbBuffer,
            }
          );
        } catch (err) {
          console.error("[THUMBNAIL UPLOAD]", err);
        }
      }

      // Update pipeline
      await pipesRef.doc(pipelineId).update({
        state: "PUBLISHED",
        "assets.youtubeVideoId": videoData.id,
        "assets.youtubeUrl": `https://youtu.be/${videoData.id}`,
        updatedAt: new Date().toISOString(),
        stateHistory: FieldValue.arrayUnion({
          state: "PUBLISHED",
          at: new Date().toISOString(),
        }),
      });

      // Log to knowledge engine for learning
      try {
        const baseUrl = process.env.NEXT_PUBLIC_BASE_URL
          || (process.env.VERCEL_PROJECT_PRODUCTION_URL ? `https://${process.env.VERCEL_PROJECT_PRODUCTION_URL}` : null)
          || (process.env.VERCEL_URL ? `https://${process.env.VERCEL_URL}` : null)
          || "http://localhost:3000";

        await fetch(`${baseUrl}/api/factory/knowledge`, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            action: "learn",
            userId,
            insight: `Published "${script.title}" in ${pipe.niche} niche on ${pipe.channelName}. Tier: ${pipe.videoTier}. Cost: $${(pipe.totalCost || 0).toFixed(2)}.`,
            outcome: "published",
            category: "publishing",
            relatedVideo: videoData.id,
            relatedChannel: pipe.channelId,
          }),
        });
      } catch { /* learning is non-critical */ }

      return Response.json({
        published: true,
        videoId: videoData.id,
        url: `https://youtu.be/${videoData.id}`,
        title: script.title,
        privacy: metadata.status.privacyStatus,
        scheduled: scheduledPublishAt || null,
      });
    }

    /* ── UPDATE METADATA on existing video ── */
    if (action === "update-metadata") {
      const { videoId, title, description, tags, category, privacy } = body;
      if (!videoId) return Response.json({ error: "videoId required" }, { status: 400 });

      const accessToken = await getGoogleToken();
      if (!accessToken) return Response.json({ error: "No Google token" }, { status: 401 });

      const update = { id: videoId, snippet: {}, status: {} };
      if (title) update.snippet.title = title;
      if (description) update.snippet.description = description;
      if (tags) update.snippet.tags = tags;
      if (category) update.snippet.categoryId = getCategoryId(category);
      if (privacy) update.status.privacyStatus = privacy;

      const parts = [];
      if (Object.keys(update.snippet).length) parts.push("snippet");
      if (Object.keys(update.status).length) parts.push("status");

      const res = await fetch(
        `https://www.googleapis.com/youtube/v3/videos?part=${parts.join(",")}`,
        {
          method: "PUT",
          headers: {
            Authorization: `Bearer ${accessToken}`,
            "Content-Type": "application/json",
          },
          body: JSON.stringify(update),
        }
      );

      if (!res.ok) {
        const errData = await res.json();
        return Response.json({ error: errData.error?.message }, { status: res.status });
      }

      return Response.json({ updated: true, videoId });
    }

    return Response.json({
      error: "action must be: publish or update-metadata",
    }, { status: 400 });
  } catch (err) {
    console.error("[FACTORY/PUBLISH]", err);
    return Response.json({ error: err.message }, { status: 500 });
  }
}

/* ── YouTube category ID mapper ── */
function getCategoryId(category) {
  const map = {
    "Film & Animation": "1",
    "Autos & Vehicles": "2",
    Music: "10",
    "Pets & Animals": "15",
    Sports: "17",
    "Short Movies": "18",
    "Travel & Events": "19",
    Gaming: "20",
    Videoblogging: "21",
    "People & Blogs": "22",
    Comedy: "23",
    Entertainment: "24",
    "News & Politics": "25",
    "Howto & Style": "26",
    Education: "27",
    "Science & Technology": "28",
    "Nonprofits & Activism": "29",
  };
  return map[category] || "24"; // Default to Entertainment
}
